"""
AG-X Community Edition — CLI

Entry point: agx
Commands:
  agx init              Create ~/.agx/ dir + sample vaccines.yaml
  agx scan              Analyze log file → print ScanReport (rich table)
  agx validate          Run cage assertions against sample output
  agx serve             Start local dashboard
  agx list-vaccines     Show active vaccines from ~/.agx/vaccines/
  agx runs              Show recent runs from SQLite
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path
from typing import Optional

import click
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box
from rich.text import Text

console = Console()


# ---------------------------------------------------------------------------
# CLI group
# ---------------------------------------------------------------------------


@click.group()
@click.version_option(package_name="agx-community", prog_name="agx")
def main() -> None:
    """AG-X Community Edition — deterministic safety guardrails for AI agents."""


# ---------------------------------------------------------------------------
# agx init
# ---------------------------------------------------------------------------


@main.command()
def init() -> None:
    """Create ~/.agx/ directory structure and a sample vaccines.yaml."""
    from agx._config import settings

    data_dir = settings.resolved_data_dir
    if data_dir is None:
        console.print("[yellow]AGX_DATA_DIR is empty — running in memory mode. Nothing to init.[/yellow]")
        return

    data_dir.mkdir(parents=True, exist_ok=True)
    vaccines_dir = data_dir / "vaccines"
    vaccines_dir.mkdir(exist_ok=True)

    sample_path = vaccines_dir / "sample_agent.yaml"
    if not sample_path.exists():
        sample_path.write_text(
            _SAMPLE_VACCINE_YAML, encoding="utf-8"
        )
        console.print(f"[green]Created sample vaccine:[/green] {sample_path}")
    else:
        console.print(f"[dim]Sample vaccine already exists:[/dim] {sample_path}")

    console.print(f"\n[bold green]✓ AG-X initialized:[/bold green] {data_dir}")
    console.print("\nNext steps:")
    console.print("  1. Decorate your agent:  [cyan]@agx.protect(agent_name='my_agent')[/cyan]")
    console.print("  2. Scan your logs:       [cyan]agx scan --input logs.jsonl[/cyan]")
    console.print("  3. Open the dashboard:   [cyan]agx serve[/cyan]")


_SAMPLE_VACCINE_YAML = """\
# AG-X Community Edition — sample vaccine file
# Generated by `agx init`
# Version-control this file to share vaccines across your team.
#
# target field values: final_output | chain_of_thought | full_output
# severity values:     WARN | BLOCK | ROLLBACK

agent_name: sample_agent
version: 1
vaccines:
  - id: vax_sample_001
    failure_category: SCHEMA_VIOLATION
    root_cause_summary: "Agent must return a JSON object with a 'result' field"
    confidence: 0.9
    cognitive_patch:
      type: PREPEND
      instruction: >
        You MUST respond with a valid JSON object only.
        Never include text, markdown, or explanation outside the JSON.
      priority: 9
      scope: GLOBAL
    executable_assertions:
      - engine: json_schema
        target: final_output
        pattern:
          type: object
          required: [result]
          properties:
            result:
              type: string
        severity: BLOCK
        description: "Output must be JSON with a result field"
      - engine: forbidden_string
        target: final_output
        pattern: "I'm sorry, I cannot"
        severity: WARN
        description: "Detect refusal responses"
"""


# ---------------------------------------------------------------------------
# agx scan
# ---------------------------------------------------------------------------


@main.command()
@click.option("--input", "-i", "input_file", required=True, help="JSONL or plain-text log file")
@click.option("--agent", "-a", "agent_name", default=None, help="Filter to one agent name")
@click.option("--output", "-o", "output_file", default=None, help="Write vaccines to YAML file")
@click.option("--dry-run", is_flag=True, default=False, help="Print report without writing files")
@click.option(
    "--exit-code",
    is_flag=True,
    default=False,
    help="Exit non-zero if BLOCK-level violations detected (CI/CD mode)",
)
def scan(
    input_file: str,
    agent_name: Optional[str],
    output_file: Optional[str],
    dry_run: bool,
    exit_code: bool,
) -> None:
    """Analyze a log file for agent failure patterns and suggest vaccines."""
    from agx.scanner.analyzer import analyze
    from agx.scanner.yaml_exporter import export_yaml
    from agx._models import VaccineManifest, AssertionSeverity

    try:
        report = analyze(input_file, agent_name=agent_name)
    except FileNotFoundError as exc:
        console.print(f"[red]Error:[/red] {exc}")
        sys.exit(1)
    except Exception as exc:
        console.print(f"[red]Scan failed:[/red] {exc}")
        sys.exit(1)

    # --- Build rich table ---
    title = (
        f"AGX Scan Report — [bold]{report.agent_name}[/bold] — "
        f"{report.total_runs} runs ({report.failure_count} failures)"
    )

    table = Table(
        title=title,
        box=box.ROUNDED,
        title_style="bold cyan",
        header_style="bold white on dark_blue",
        show_lines=True,
    )
    table.add_column("Pattern", style="cyan", min_width=20)
    table.add_column("Count", justify="right", min_width=10)
    table.add_column("Suggested Action", min_width=25)

    for pattern in report.patterns:
        count_str = f"{pattern.count} ({pattern.percentage}%)"
        if pattern.suggested_assertion:
            sev = pattern.suggested_assertion.severity.value
            eng = pattern.suggested_assertion.engine.value
            action_style = "red bold" if sev == "BLOCK" else "yellow"
            action = Text(f"{eng} {sev}", style=action_style)
        else:
            action = Text("—", style="dim")
        table.add_row(pattern.category.value, count_str, action)

    console.print()
    console.print(table)

    # --- Heuristic confidence disclaimer (refinement #2) ---
    console.print(
        Panel(
            "[yellow]⚠️  Heuristic-based suggestions.[/yellow] "
            "Run [cyan]agx validate[/cyan] against historical outputs\n"
            "to measure false positive rate before committing to production.\n"
            "For ML-powered vaccine generation with backtesting, upgrade to [bold]AG-X Cloud[/bold].",
            border_style="yellow",
            padding=(0, 2),
        )
    )

    # --- Write output ---
    if report.suggested_vaccines and not dry_run:
        dest = output_file
        if dest is None:
            from agx._config import settings
            vd = settings.vaccines_dir
            if vd:
                dest = str(vd / f"{report.agent_name}.yaml")

        if dest:
            manifest = VaccineManifest(
                agent_name=report.agent_name,
                vaccines=report.suggested_vaccines,
            )
            try:
                export_yaml(manifest, dest)
                console.print(f"\n[green]Vaccines written to:[/green] {dest}")
                console.print(f"[dim]Run: agx validate --vaccine {dest}[/dim]")
            except Exception as exc:
                console.print(f"[red]Failed to write vaccines:[/red] {exc}")
    elif dry_run:
        console.print("\n[dim](dry-run mode — vaccines not written)[/dim]")

    # --- Optional LLM enhancement ---
    import os
    if os.environ.get("OPENAI_API_KEY") or os.environ.get("GROQ_API_KEY"):
        try:
            from agx.scanner.llm_doctor import enhance_with_llm
            extra = enhance_with_llm(report, report.agent_name)
            if extra:
                console.print(f"\n[cyan]LLM doctor added {len(extra)} additional vaccine(s).[/cyan]")
        except Exception:
            pass

    # --- CI exit code (refinement #4) ---
    if exit_code and report.has_block_violations:
        console.print(
            "\n[red bold]✗ BLOCK-level violations detected. Exiting with code 1 (CI mode).[/red bold]"
        )
        sys.exit(1)


# ---------------------------------------------------------------------------
# agx validate
# ---------------------------------------------------------------------------


@main.command()
@click.option("--vaccine", "-v", "vaccine_file", required=True, help="Vaccine YAML file")
@click.option("--test-output", "-t", "test_output", required=True, help="JSON string or plain text to validate")
def validate(vaccine_file: str, test_output: str) -> None:
    """Run cage assertions from a vaccine file against a sample output."""
    from agx.cage import DeterministicCage
    from agx.scanner.yaml_exporter import import_yaml

    try:
        manifest = import_yaml(vaccine_file)
    except FileNotFoundError as exc:
        console.print(f"[red]Error:[/red] {exc}")
        sys.exit(1)
    except Exception as exc:
        console.print(f"[red]Failed to load vaccine:[/red] {exc}")
        sys.exit(1)

    assertions = []
    for vaccine in manifest.vaccines:
        assertions.extend(vaccine.executable_assertions)

    if not assertions:
        console.print("[yellow]No executable assertions found in vaccine file.[/yellow]")
        return

    cage = DeterministicCage(assertions=assertions)
    result = cage.run(test_output)

    table = Table(
        title=f"Cage Validation — {manifest.agent_name}",
        box=box.ROUNDED,
        title_style="bold cyan",
        header_style="bold",
    )
    table.add_column("Engine", style="cyan", min_width=15)
    table.add_column("Target", min_width=14)
    table.add_column("Severity", min_width=10)
    table.add_column("Result", min_width=8)
    table.add_column("Message")

    for verdict in result.verdicts:
        a = verdict.assertion
        passed_icon = "[green]✓ PASS[/green]" if verdict.passed else "[red]✗ FAIL[/red]"
        sev_style = "red" if a.severity.value == "BLOCK" else "yellow"
        table.add_row(
            a.engine.value,
            a.target.value,
            Text(a.severity.value, style=sev_style),
            Text(passed_icon),
            verdict.message,
        )

    console.print()
    console.print(table)

    if result.passed:
        console.print("\n[bold green]✓ All assertions passed.[/bold green]")
    else:
        failed = [v for v in result.verdicts if not v.passed]
        console.print(f"\n[bold red]✗ {len(failed)} assertion(s) failed.[/bold red]")
        if result.blocked:
            console.print("[red]Output would be BLOCKED by the guard.[/red]")
            sys.exit(1)


# ---------------------------------------------------------------------------
# agx serve
# ---------------------------------------------------------------------------


@main.command()
@click.option("--port", "-p", default=7000, show_default=True, help="Dashboard port")
@click.option("--host", default="127.0.0.1", show_default=True, help="Bind host")
def serve(port: int, host: str) -> None:
    """Start the local AG-X dashboard."""
    try:
        from agx.dashboard.server import run as run_server
    except ImportError:
        console.print(
            "[red]Dashboard dependencies not installed.[/red]\n"
            "Run: [cyan]pip install agx-community[dashboard][/cyan]"
        )
        sys.exit(1)

    console.print(
        Panel(
            f"[bold green]AG-X Dashboard[/bold green]\n\n"
            f"  [cyan]http://{host}:{port}/[/cyan]         Runs list\n"
            f"  [cyan]http://{host}:{port}/vaccines[/cyan]  Active vaccines\n"
            f"  [cyan]http://{host}:{port}/scanner[/cyan]   Log scanner\n\n"
            f"Press [bold]Ctrl+C[/bold] to stop.",
            border_style="green",
            title="🛡️ AG-X Community",
        )
    )
    run_server(host=host, port=port)


# ---------------------------------------------------------------------------
# agx list-vaccines
# ---------------------------------------------------------------------------


@main.command("list-vaccines")
def list_vaccines() -> None:
    """Show all active vaccines from ~/.agx/vaccines/."""
    from agx.store import get_store

    store = get_store()
    manifests = store.list_all_vaccines()

    if not manifests:
        console.print("[dim]No vaccine files found in ~/.agx/vaccines/[/dim]")
        console.print("Run [cyan]agx scan[/cyan] to generate vaccines.")
        return

    for manifest in manifests:
        console.print(
            f"\n[bold cyan]{manifest.agent_name}[/bold cyan] "
            f"[dim](v{manifest.version}, {len(manifest.vaccines)} vaccine(s))[/dim]"
        )
        for vaccine in manifest.vaccines:
            console.print(f"  [dim]{vaccine.id}[/dim]  {vaccine.failure_category.value}  "
                          f"confidence={int(vaccine.confidence * 100)}%")
            if vaccine.executable_assertions:
                for a in vaccine.executable_assertions:
                    sev_style = "red" if a.severity.value == "BLOCK" else "yellow"
                    console.print(
                        f"    [{sev_style}]{a.severity.value}[/{sev_style}] "
                        f"{a.engine.value} → {str(a.pattern)[:60]}"
                    )


# ---------------------------------------------------------------------------
# agx runs
# ---------------------------------------------------------------------------


@main.command()
@click.option("--limit", "-n", default=50, show_default=True, help="Number of runs to show")
@click.option("--agent", "-a", default=None, help="Filter by agent name")
def runs(limit: int, agent: Optional[str]) -> None:
    """Show recent agent runs from the local SQLite store."""
    from agx.store import get_store

    async def _fetch():
        store = get_store()
        return await store.list_runs(agent_name=agent, limit=limit)

    rows = asyncio.run(_fetch())

    if not rows:
        console.print("[dim]No runs recorded yet.[/dim]")
        console.print("Decorate an agent with [cyan]@agx.protect[/cyan] to start tracing.")
        return

    table = Table(
        title=f"Recent Runs (last {limit})",
        box=box.ROUNDED,
        title_style="bold cyan",
        header_style="bold",
    )
    table.add_column("Agent", style="cyan", min_width=16)
    table.add_column("Outcome", min_width=10)
    table.add_column("Cage", min_width=6, justify="center")
    table.add_column("Duration", justify="right", min_width=10)
    table.add_column("Timestamp", min_width=19)

    for row in rows:
        outcome = row.get("outcome", "—")
        outcome_style = {
            "SUCCESS": "green",
            "FAILURE": "red",
            "BLOCKED": "dark_orange",
            "WARNED": "yellow",
        }.get(outcome, "white")

        cage_passed = row.get("cage_passed")
        cage_icon = "✓" if cage_passed == 1 else ("✗" if cage_passed == 0 else "—")
        cage_style = "green" if cage_passed == 1 else ("red" if cage_passed == 0 else "dim")

        ms = row.get("total_ms")
        ms_str = f"{ms:.0f}ms" if ms is not None else "—"

        ts = (row.get("timestamp") or "")[:19]

        table.add_row(
            row.get("agent_name", "—"),
            Text(outcome, style=outcome_style),
            Text(cage_icon, style=cage_style),
            ms_str,
            ts,
        )

    console.print()
    console.print(table)
