"""
AG-X Community Edition — YAML vaccine exporter / importer

Handles serializing VaccineManifest objects to/from human-readable YAML files.
The YAML format is designed to be git-committable and team-shareable.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Union

import yaml

from agx._models import VaccineManifest


def export_yaml(manifest: VaccineManifest, output_path: Union[str, Path]) -> Path:
    """Write a VaccineManifest to a YAML file.

    The file is formatted for human readability:
    - agent_name and version at the top
    - vaccines list with full structure
    - no Python-specific YAML tags

    Returns the resolved output path.
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    # Convert via JSON to strip Pydantic internals and enums → plain strings
    raw = json.loads(manifest.model_dump_json())

    # Write a header comment
    header = (
        f"# AG-X Community Edition — Vaccine file for '{manifest.agent_name}'\n"
        "# Generated by `agx scan`. Edit manually or re-generate.\n"
        "# Version-control this file to share vaccines across your team.\n"
        "#\n"
        "# target field values: final_output | chain_of_thought | full_output\n"
        "# severity values:     WARN | BLOCK | ROLLBACK\n"
        "# cognitive_patch.type: PREPEND | APPEND | REPLACE | INJECT_RULE\n\n"
    )

    body = yaml.dump(raw, allow_unicode=True, sort_keys=False, default_flow_style=False)
    path.write_text(header + body, encoding="utf-8")
    return path


def import_yaml(input_path: Union[str, Path]) -> VaccineManifest:
    """Read a VaccineManifest from a YAML file.

    Raises FileNotFoundError if the file does not exist.
    Raises pydantic.ValidationError if the YAML structure is invalid.
    """
    path = Path(input_path)
    if not path.exists():
        raise FileNotFoundError(f"Vaccine file not found: {path}")

    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return VaccineManifest.model_validate(raw)
